title: "Rivéo"
description: "Suivi des rivières par caméra — publication ouverte des jeux de données"
url: "https://riveo-hydro.github.io/"        
baseurl: ""                              

# Thème Minimal Mistakes (via gem OU remote_theme). Ici via gem:
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Dossiers utiles
include:
  - _pages
  - data

# Options MM (basique)  # autres: air, contrast, dark, dirt, neon...
locale: fr-FR

logo: /assets/images/logo.png
masthead_title: ""

# Navigation (exemple)
nav:
  - title: "Accueil"
    url: /
  - title: "Jeux de données"
    url: /data/
  - title: "Documentation"
    url: /docs/
  - title: "À propos"
    url: /a-propos/

# Permaliens plus jolis
permalink: /:categories/:title/


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      toc: false
      classes: wide
  - scope:
      path: "data"
      type: "pages"
    values:
      layout: single
      toc: false
      classes: wide
      
# Build
markdown: kramdown
kramdown:
  input: GFM



